"""
app/models/explanation.py
──────────────────────────
Explanation ORM model — stores SHAP and GNNExplainer outputs.

Source: Chapter 4, Section 4.13
Quote: "A risk score alone is of limited practical value... the system
         therefore pairs every prediction with an explanation, generated by
         combining two complementary techniques: SHAP (Feature Importance)
         and GNNExplainer (Node and Edge Importance)."
"""

from __future__ import annotations

import uuid
from typing import TYPE_CHECKING, Any

from sqlalchemy import Float, ForeignKey, Text, UniqueConstraint
from sqlalchemy.dialects.postgresql import JSONB, UUID as PgUUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database.base import Base
from app.models.mixins import TimestampMixin, UUIDPrimaryKeyMixin

if TYPE_CHECKING:
    from app.models.prediction import Prediction
    from app.models.token import Token


class Explanation(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    """
    Combined SHAP and GNNExplainer output for a single prediction.
    Separated from the predictions table because JSONB payloads can be large.
    Ch4 §4.13.
    """

    __tablename__ = "explanations"
    __table_args__ = (
        UniqueConstraint("prediction_id", name="uq_explanations_prediction_id"),
        {
            "comment": (
                "Combined SHAP (feature) and GNNExplainer (graph) explanations. "
                "Ch4 §4.13."
            )
        },
    )

    # ── FKs ───────────────────────────────────────────────────
    prediction_id: Mapped[uuid.UUID | None] = mapped_column(
        PgUUID(as_uuid=True),
        ForeignKey("predictions.id", ondelete="CASCADE"),
        nullable=True,
    )
    token_id: Mapped[uuid.UUID] = mapped_column(
        PgUUID(as_uuid=True),
        ForeignKey("tokens.id", ondelete="CASCADE"),
        nullable=False,
    )

    # ── SHAP: Feature Importance (Ch4 §4.13.1) ────────────────
    shap_base_value: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
        comment="Base value (expected risk) before feature contributions",
    )
    shap_values: Mapped[dict[str, Any] | None] = mapped_column(
        JSONB,
        nullable=True,
        comment="Dictionary of {feature_name: shap_value}",
    )
    shap_top_features: Mapped[dict[str, Any] | None] = mapped_column(
        JSONB,
        nullable=True,
        comment="Ordered list of top features by absolute SHAP value",
    )

    # ── GNNExplainer: Subgraph Importance (Ch4 §4.13.2) ───────
    important_node_ids: Mapped[list[Any] | None] = mapped_column(
        JSONB,
        nullable=True,
        comment="List of wallet addresses/node IDs in the minimal subgraph",
    )
    important_edge_ids: Mapped[list[Any] | None] = mapped_column(
        JSONB,
        nullable=True,
        comment="List of (src, dst, timestamp) edges in the minimal subgraph",
    )
    node_importance_scores: Mapped[dict[str, Any] | None] = mapped_column(
        JSONB,
        nullable=True,
        comment="Dictionary of {node_id: importance_score}",
    )
    edge_importance_scores: Mapped[dict[str, Any] | None] = mapped_column(
        JSONB,
        nullable=True,
        comment="Dictionary of {edge_id: importance_score}",
    )

    # ── Narrative Summary (Ch4 §4.13.3) ───────────────────────
    risk_summary_text: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="Human-readable synthesis combining SHAP and GNNExplainer results",
    )

    # ── Relationships ─────────────────────────────────────────
    prediction: Mapped[Prediction] = relationship(
        "Prediction",
        back_populates="explanation",
        foreign_keys="[Prediction.explanation_id]",
    )
    token: Mapped[Token] = relationship(
        "Token",
        back_populates="explanations",
    )

    def __repr__(self) -> str:
        return f"<Explanation {self.id} token={self.token_id}>"
