"""
app/models/mixins.py
─────────────────────
Reusable SQLAlchemy column mixins for common fields.
Applied via multiple inheritance on model classes.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import DateTime, text
from sqlalchemy.dialects.postgresql import UUID as PgUUID
from sqlalchemy.orm import Mapped, mapped_column
from sqlalchemy.sql import func


class UUIDPrimaryKeyMixin:
    """
    UUID primary key generated by PostgreSQL's gen_random_uuid().
    Using server-side generation ensures uniqueness even when
    multiple application instances insert concurrently.
    """

    id: Mapped[uuid.UUID] = mapped_column(
        PgUUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
        comment="Surrogate primary key (UUID v4, server-generated)",
    )


class TimestampMixin:
    """Immutable created_at timestamp for append-only and audit tables."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
        comment="Row creation timestamp (UTC)",
    )


class FullTimestampMixin(TimestampMixin):
    """
    Both created_at and updated_at.
    updated_at is maintained by the application layer on every flush.
    """

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
        comment="Last modification timestamp (UTC)",
    )
